//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login_Role
    {
        public int Login_Role_ID { get; set; }
        public Nullable<int> Login_ID { get; set; }
        public Nullable<int> Role_ID { get; set; }
        public string Page1 { get; set; }
    
        public virtual Login Login { get; set; }
        public virtual Role1 Role1 { get; set; }
    }
}
