//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Web
{
    using System;
    using System.Collections.Generic;
    
    public partial class Not_Coming
    {
        public int Not_Coming_ID { get; set; }
        public Nullable<int> Doctor_ID { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string Status { get; set; }
    
        public virtual Doctor Doctor { get; set; }
    }
}
