//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Channel
    {
        public int Channel_ID { get; set; }
        public Nullable<int> Doctor_ID { get; set; }
        public Nullable<System.DateTime> Channel_Date1 { get; set; }
        public Nullable<System.DateTime> Channel_Date2 { get; set; }
        public string Status { get; set; }
        public string No1 { get; set; }
        public string Contact1 { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Work_Date_ID { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual User_Details User_Details { get; set; }
    }
}
