//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Home_Visit
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Home_Visit()
        {
            this.Sick_Visit = new HashSet<Sick_Visit>();
        }
    
        public int Home_Visit_ID { get; set; }
        public Nullable<int> Doctor_ID { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public string Status { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual User_Details User_Details { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sick_Visit> Sick_Visit { get; set; }
    }
}
