//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Login
    {
        public int Login_ID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string Status { get; set; }
        public Nullable<int> User_ID { get; set; }
        public Nullable<int> Role_ID { get; set; }
    
        public virtual Role1 Role1 { get; set; }
        public virtual User_Details User_Details { get; set; }
    }
}
