//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Web.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Hospital_WebEntities : DbContext
    {
        public Hospital_WebEntities()
            : base("name=Hospital_WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Channel> Channels { get; set; }
        public virtual DbSet<Date1> Date1 { get; set; }
        public virtual DbSet<Doctor> Doctors { get; set; }
        public virtual DbSet<Home_Visit> Home_Visit { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<Not_Coming> Not_Coming { get; set; }
        public virtual DbSet<Page1> Page1 { get; set; }
        public virtual DbSet<Role_Page> Role_Page { get; set; }
        public virtual DbSet<Role1> Role1 { get; set; }
        public virtual DbSet<Sick> Sicks { get; set; }
        public virtual DbSet<Sick_Visit> Sick_Visit { get; set; }
        public virtual DbSet<Specialty> Specialties { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<User_Details> User_Details { get; set; }
        public virtual DbSet<Work_Date> Work_Date { get; set; }
    }
}
