//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sick_Visit
    {
        public int Sick_Visit_ID { get; set; }
        public Nullable<int> Home_Visit_ID { get; set; }
        public Nullable<int> Sick_ID { get; set; }
        public string Status { get; set; }
    
        public virtual Home_Visit Home_Visit { get; set; }
        public virtual Sick Sick { get; set; }
    }
}
