//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hospital_Web.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Work_Date
    {
        public int Work_Date_ID { get; set; }
        public Nullable<int> Date_ID { get; set; }
        public Nullable<int> Doctor_ID { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Start_Time { get; set; }
        public Nullable<System.DateTime> End_Time { get; set; }
        public Nullable<int> Max_Patient { get; set; }
    
        public virtual Date1 Date1 { get; set; }
        public virtual Doctor Doctor { get; set; }
    }
}
